### PR TITLE
Add wrf content from current CMS wiki

### PR DESCRIPTION
**Pull request by rkutteh**
Modified file models-wrf.md and added 7 new files models-wrf-[1 to 7].md and 2 new images WRF_v4.1.3_SU_per_model_day.png and WRF_v4.1.3_Walltime_per_model_day.png. Double checked all. Just need to ensure the relative file links work as expected on GitHub.

### CODE REVIEW

**Comment by rkutteh** [comment]
Yes, just checked, internal relative links work fine. Forgot to mention that I have also ditched http://climate-cms.wikis.unsw.edu.au/WRF_tests   as it appears obsolete. I can always add if still needed.

**Review by paolap — CHANGES_REQUESTED** [review]
move the deprecated wrf config to "resources" as anything which is there for historical reasons or for our reference

**Comment by rkutteh** [comment]
@paolap I noticed that GitHub adds automatically a horizontal line under each header, which my local Markdown previewer does not display. As a result there is too many lines displayed now in the wrf files on GitHub. I will fix this issue on my next commit.

**Comment by paolap** [comment]
There is now a resource folder in the main branch, I think the best way forward would be to pull the current main into this branch, then move the "obsolete' WRF file and then commit and push again. Hopefully, there won't be many conflicts, most likely there will be some in the index _toc.yml file

**Comment by paolap** [comment]
@rkutteh I did some modification mostly to the formatting:

* added the models-wrf-#.md files to the index _toc.yaml
* removed the extra # at the end of the headers and the lines underneath them
* made sure the header level was correct and consistent
* removed newlines in the middle of sentences, I'm not sure if that is a result of copy&paste or intentional, but they don't work as the text still will go onto a newline only if explicitly set with {br} and it caused issues in some cases where the newline wasn't recognised
* add where suitable warning and/or note boxes 
* added some text where a chapter started with no introduction to what the page was
* switched the order of updates vs installation in the first page, so know the install/run etc info comes first.
*  finally I changed the name of the file moved to resources to reflect what it is
I get the feeling that lots of this content is obsolete, I'm not sure how much the updates are useful still and there's a page on how to run WRF with ERAI but not ERA5. Also the netcdf file page is so short can probably be integrated with the tips page.
 We should also consider that the tips is very similar content to the FAQS so that might be a better place for it?? Or at least we should be consistent with whatever we will do for the other models.
Thanks for doing this, I'll merge now, but I'll leave the issue open to keep the comments on future improvement visible.

**Pull request merged**
