### PR TITLE
Faqs and tips

### PR DESCRIPTION
**Pull request by greensh16**
Added the Faqs and Tips page, copied all info from the old wiki for now. Created topics and added all relevant faqs to them to make the whole page a bit easier to navigate.

### CODE REVIEW

**Review by paolap — CHANGES_REQUESTED** [review]
I think we should remove the table of contents at the start as it is redundant as all the headers are shown anyway on a side panel. After that is fine to merge. This will need some restructuring as the original structure/formatting was awful, but it can be done after the merge

**Comment by greensh16** [comment]
Oops I completely missed the contents bar on the right. 

I'm restructuring this a bit, do you think it would look ok to create a new section in the left panel called 'FAQS' and within that have a general faqs page (the one that I currently have) and then individual pages for the MOM, UM, ACCESS, WRF, CESM Faqs. Maybe even have individual pages for python, Gadi, Fortran, etc?  Or would that look too messy

**Comment by paolap** [comment]
That might work, some pages might be quite small but then we can work on the right granularity later. i.e. maybe we can put all the model FAQS together. I think it would be great to have a section just for that as that will give them a lot more visibility which is what we want. And we can still move stuff around later, so give it a go, I think it's a good idea

**Comment by greensh16** [comment]
Ok I've set up a new layout for all the FAQs pages, tried to keep it as clean as possible. What do you think?

**Comment by paolap** [comment]
I've merged this, after resolving the conflicts in the index. So it's easier to discuss this at the next meeting, and a lot of content might need updating, so I think for the moment is enough, thanks :-)

**Review by paolap — COMMENTED** [review]
All good

**Review by paolap — APPROVED** [review]

**Pull request merged**
